### ISSUE TITLE
Provide required / supported versions

### ISSUE THREAD

**Issue by mathrack** [2decomp-fft/2decomp-fft#179]
The readme should be more explicit for the supported versions of various libraries (or at least a version known to work) :

- Supported versions for FFTW and Caliper are provided
- Fortran => I suspect we are using the 2008 standard ?
- MPI => I suspect we are using the version 2.x ?
- Intel MKL ?
- cudafor / nccl / cufft ?

**Comment by pbartholomew08** [comment]
The MKL I have used is MKL 2023.0.0

**Comment by rfj82982** [comment]
CUDA/NVHPC is a bit tricky to give a version since a new appear every 3 months. Generally I am using the latest. I am sure that everything works until NVHPC 22.7 and CUDA11.8. I have tested also NVHPC23.1 and CUDA12 it is working on standard Linux distribution, but not on our cluster.
