### ISSUE TITLE
CI is broken since fec20d262f002450a567028d98516dcb5562d24e

### ISSUE THREAD

**Issue by mathrack** [2decomp-fft/2decomp-fft#181]
The Caliper CI is currently broken : https://github.com/xcompact3d/2decomp-fft/actions/runs/4736855988/jobs/8408933909

It is broken since https://github.com/xcompact3d/2decomp-fft/commit/fec20d262f002450a567028d98516dcb5562d24e

**Comment by pbartholomew08** [comment]
The configuration is a bit hairy with cmake, automating it might be difficult.

**Comment by mathrack** [comment]
I think we have two options  : 

- Remove the Caliper build from the CI
- Fix it

I can not reproduce the error on my workstation so it is not easy to fix it from my perspective.

**Comment by pbartholomew08** [comment]
I haven't tried recently, will see if I can reproduce

**Comment by rfj82982** [comment]
I’ll also try the build with caliper

**Comment by mathrack** [comment]
Good news !
