### ISSUE TITLE
Intel Compiler

### ISSUE THREAD

**Issue by rfj82982** [2decomp-fft/2decomp-fft#211]
**Describe the bug**
There are sone minor issues with the Intel compiler mainly related to the new IntelLLVM. To compile and run flags needs to be differentiate between the two compilers. 
The ifx has also the following bug: 
- sqrt(1.0) return 0.9999 instead of 1 and this create an issue in serial since the decomposition routine do not  return a 1x1 decomposition but a rather 0xLargeInt

Additionally some safety checks design to check the existence of directories before running a test using the Fortran function `inquire` have a different behaviour than with other compilers returning always a `false` flag even if the directory exists. Intel fortran `inquire` functionality return `true` only if a file exists.

**Comment by pbartholomew08** [comment]
Can this be closed now?

**Comment by rfj82982** [comment]
yes
