### ISSUE TITLE
Add complex number support for ADIOS2

### ISSUE THREAD

**Issue by pbartholomew08** [2decomp-fft/2decomp-fft#229]
ADIOS2 interface was implemented based on Xcompact3d needs. ADIOS2 itself supports complex numbers, however the interface we now have does not, this should be restored for the more general use case of 2DECOMP&FFT

**Comment by mathrack** [comment]
Hello, I think it would be easier to include this improvement in version 2.1 when the IO wil be redesigned. See https://github.com/2decomp-fft/2decomp-fft/blob/refactor_io/src/io_objects.f90

**Comment by mathrack** [comment]
Fixed in https://github.com/2decomp-fft/2decomp-fft/pull/269
