### ISSUE TITLE
amd-fftw backend

### ISSUE THREAD

**Issue by mathrack** [2decomp-fft/2decomp-fft#243]
Hello,

The FFTW backend is supported. Are there plans to support [amd-fftw](https://github.com/amd/amd-fftw) ? The version 4.1 was recently released and could bring slight performance improvements compared with FFTW on AMD CPUs.

**Comment by pbartholomew08** [comment]
It should be linked by the compiler, e.g. cray-fftw is used via the fftw interface

**Comment by mathrack** [comment]
Thank you for your answer. Do we have feedback on using the AMD compiler + amd-fftw ? Shall we update the readme to mention things such as cray-fftw and amd-fftw ?

**Comment by pbartholomew08** [comment]
I've not used either the AMD compiler or fftw. We could mention that the FFTW interface should support vendor libraries - I've used the armpl verison in the past through that (I think, I should double check...).

**Comment by ningli-amd** [comment]
2decomp-fft can not be built with AOCC now (see #245)

amdfftw, part of the AOCL library, is distributed with both AOCC and GCC binary. So even if using GCC on AMD hardware, amdfftw can be used. 

Its support should be very easy.

**Comment by pbartholomew08** [comment]
Since #246 we can link AOCL/FFTW using (at least) the AOCC compilers via the existing fftw interfaces (tested with `fftw_f03`).
