### ISSUE TITLE
Fortran submodule use not working with AOCC compiler

### ISSUE THREAD

**Issue by ningli-amd** [2decomp-fft/2decomp-fft#245]
When compiling 2decomp-fft with AOCC compiler v4.0 and v4.1, the following error is seen:
```
[ 10%] Building Fortran object src/CMakeFiles/decomp2d.dir/decomp_2d_constants.f90.o
[ 20%] Building Fortran object src/CMakeFiles/decomp2d.dir/decomp_2d_mpi.f90.o
[ 30%] Building Fortran object src/CMakeFiles/decomp2d.dir/factor.f90.o
[ 40%] Building Fortran object src/CMakeFiles/decomp2d.dir/decomp_2d.f90.o
[ 50%] Building Fortran object src/CMakeFiles/decomp2d.dir/glassman.f90.o
[ 60%] Building Fortran object src/CMakeFiles/decomp2d.dir/fft_generic.f90.o
[ 70%] Building Fortran object src/CMakeFiles/decomp2d.dir/fft_log.f90.o
F90-S-0188-Argument number 1 to decomp_info_print: type mismatch (/work/ningli12/apps/2decomp-fft-2.0/src/fft_log.f90: 53)
F90-S-0038-Symbol, ph, has not been explicitly declared (/work/ningli12/apps/2decomp-fft-2.0/src/fft_log.f90)
  0 inform,   0 warnings,   2 severes, 0 fatal for decomp_2d_fft_log
make[2]: *** [src/CMakeFiles/decomp2d.dir/build.make:179: src/CMakeFiles/decomp2d.dir/fft_log.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: src/CMakeFiles/decomp2d.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
This error is about the Fortran submodule not being able to access private entities defined in the ancestor module. 

There is not much can be done as this needs to be fixed in the compiler.

**Comment by mathrack** [comment]
A related issue popped up recently. @ningli-amd do you know if there are plans to improve the support of fortran submodules in the compiler ?

**Comment by ningli-amd** [comment]
Hi @mathrack - I have just checked there is no progress on this in the Classic Flang, whose Fortran submodule support is still not complete. On the other hand, AMD has announced that in the coming AOCC 6.0 release there will be a new LLVM-based Fortran frontend. I can confirm that new Fortran compiler will not suffer from the same submodule issue. I will keep you updated once the new compiler becomes publicly available.

**Comment by mathrack** [comment]
Thank you for your feedback. This is good news ! Cheers.
