### ISSUE TITLE
Add a NONE profiling interface

### ISSUE THREAD

**Issue by pbartholomew08** [2decomp-fft/2decomp-fft#291]
**Is your feature request related to a problem? Please describe.**
The code has many `#ifdef ...` which makes it harder to read, one area where these occur is when interfacing with the profiler.

**Describe the solution you'd like**
A NONE profiler interface would allow us to remove the `#ifdef` and user code would just call `decomp_profiler_start(name)`, etc. This would then resolve to the implementation in the selected profiler backend, in the case of NONE an empty subroutine call.

**Comment by rfj82982** [comment]
I am for removing all the `#IFDEF` they are useful but they tend to mess too much the code

**Comment by rfj82982** [comment]
Starting with the profiler would be very good

**Comment by pbartholomew08** [comment]
> I am for removing all the `#IFDEF` they are useful but they tend to mess too much the code

I've opened a project for this as it's bigger than a single issue / PR

**Comment by pbartholomew08** [comment]
> I need to add also the nvhpc profiler to the options since it is useful for GPU.

Have we tried using the caliper interface directly? Apparently it should integrate with NVTX https://software.llnl.gov/Caliper/ThirdPartyTools.html
