### ISSUE TITLE
Re-design IO logic

### ISSUE THREAD

**Issue by mathrack** [2decomp-fft/2decomp-fft#33]
Some progress on this issue is possible after issue [https://github.com/xcompact3d/2decomp-fft/issues/9](https://github.com/xcompact3d/2decomp-fft/issues/9) is solved.

The proposed IO logic would rely on a list of readers and writers.

### A reader / writer

1. Would perform IO using MPI, ADIOS2, raw binary or text (only one). MPI and ADIOS2 correspond to parallel IO. Raw binary and text correspond to serial IO. ADIOS2 could also correspond to serial IO.
2. Can do IO using single or double precision but not both (whatever the value of the variable `mytype`)
3. Can do IO for real and complex variables, integers and logicals
4. Can do parallel IO only for fields associated with a given decomp_info object
5. Can do parallel IO for 3D scalars and 2D slices
6. Can do serial IO for 1D profiles and 0D probes
7. Can perform transpose operations in case of parallel IO with native precision
8. Can perform MPI operations in case of serial IO

### A reader object should include the following information

1. Read at the beginning of the simulation ?
2. Read at a given frequency ? (probably at the beginning of the time step, but this is out of the scope of decomp_2d)
3. Id of the reader (unique)
4. Name of the reader (unique)
5. Directory for the reader
6. Optional, number of files / variables the reader is associated with (a reader can read several files / variables)
7. Optional, names of the files / variables the reader is associated with (a reader can read several files / variables)
8. If parallel IO, associated decomp_info object

### A writer object should include the following information

1. Write at the beginning of the simulation ?
2. Write at the end of the simulation ?
3. Write at a given frequency ? (probably at the end of the time step, but this is out of the scope of decomp_2d)
4. Id of the writer (unique)
5. Name of the writer (unique)
9. Directory for the writer
10. Optional, number of files / variables the writer is associated with (a writer can write several files / variables)
11. Optional, names of the files / variables the writer is associated with (a writer can write several files / variables)
12. If parallel IO, optional, is-it coarse-grained ?
13. If parallel IO, associated decomp_info object

**Comment by pbartholomew08** [comment]
I think this will be good to discuss in person in September, before we do any changes like this I'd like to do some tidying (e.g. lift all the MPIIO stuff into an `io_mpiio` submodule and likewise ADIOS2 into `io_adios2` submodule) this should make it easier for the two to work together and clean up the code to make significant logic changes easier to implement.

**Comment by mathrack** [comment]
Some ideas for refactoring IO can be found here : https://github.com/xcompact3d/2decomp-fft/tree/refactor_io

**Comment by mathrack** [comment]
The discussion is outdated, closing.
