### ISSUE TITLE
DCT-DFT-DFT or nothing-DFT-DFT

### ISSUE THREAD

**Issue by BenMql** [2decomp-fft/2decomp-fft#337]
Greetings, 

I am developing and using [Coral](https://github.com/benmql/coral), a parallel spectral solver for partial differential equations in the plane layer geometry. Coral relies on a Chebyshev-Fourier-Fourier decomposition of the variables, which would be a great (and, I believe, reasonably easy) additional feature for `2decomp`. 

[A few years ago, I modified 2decomp v1.5  (more precisely, the ./src/fft_fftw_f03.f90 file)](https://github.com/BenMql/2decomp_emptyFourierFourier/) in order to add the flag `IN_CORE_CHEBYSHEV`. When initialised with this flag, the modified 2decomp library essentially behaves similarly to `PHYSICAL_IN_Z`, except that the transform along the contiguous dimension is skipped. Hence, in-core DCT can be computed (serially) by external routines, before calling 2decomp_fft complex to real transforms. This paves the way for DCT-DFT-DFT transforms, and resolution of PDEs in the plane layer geometry.

Currently, `Coral` can be either linked against `fftw-mpi` (for a 1D, slab domain decomposition), or against the modified 2decomp v1.5 described above. The issue is that this clunky patch is based on a deprecated version of the library, and it is rather unpractical for me to patch more recent versions as they are published. 
On the other hand, it seems that it would advantageously expand the scope of 2decomp to officially support DCT-DFT-DFT (or even empty-DFT-DFT, and let the user compute the in-core DCT himself). The [modified source file](https://github.com/BenMql/2decomp_emptyFourierFourier/blob/main/src/fft_fftw3_f03.f90) may contain all the tricks necessary for the implementation (by searching for `IN_CORE_CHEBYSHEV` and `BM patch`)

In addition, I would be happy to contribute if I can.

Best,
--Ben Miquel

**Comment by mathrack** [comment]
Hello,

Thank you for your suggestion, we will look into it. The current sketch is interesting but probably not very generic.

One way to make this generic could be to add an optional argument (`logical, dimension(3)`) allowing to skip a complex-to-complex 1D transform in r2c, c2r and c2c transforms.

**Comment by BenMql** [comment]
Thank you for your swift reply. Your proposed solution indeed sounds sensible to me.

**Comment by rfj82982** [comment]
The best would be if you can try to merge them in the current version of 2DECOMP&FFT and to a draft PR. With this we can have a more in depth look at the code and potentially merge it. 

Stefano
